version: 2

builds:
  - main: ./cmd/archy
    binary: archy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary

changelog:
  sort: asc
